In [58]:
import numpy as np
import pandas as pd

Question 1: Global Class Distribution & Clean Sample Mass
In data/public/train.csv, each of the 11,393 unique training images has 4 rows corresponding to the 4 defect classes (defect_a, defect_b, defect_c, defect_d), totaling 45,572 rows. A row with empty/null mask_rle indicates the absence of that defect.

Compute the frequency distribution of positive occurrences for each defect class, as well as the total number of completely clean images (images with no defect across all 4 classes).

Question: Based on your calculations, what is the exact sum of the count of positive samples in the most frequent defect class and the total count of completely clean images?

Answer format: Integer.

In [59]:
df = pd.read_csv(r'D:\SurfaceGuard_AI\data\train.csv')
df.head(10)

,image_id,defect_type,mask_rle,width,height
0,4S22I7SA34,defect_a,7255 6 7377 12 7505 12 7633 12 7762 11 7890 11...,800,128
1,4S22I7SA34,defect_b,NaN,800,128
2,4S22I7SA34,defect_c,NaN,800,128
3,4S22I7SA34,defect_d,NaN,800,128
4,DZ899111OE,defect_a,NaN,800,128
5,DZ899111OE,defect_b,NaN,800,128
6,DZ899111OE,defect_c,NaN,800,128
7,DZ899111OE,defect_d,NaN,800,128
8,GVDJ3PQ5QT,defect_a,NaN,800,128
9,GVDJ3PQ5QT,defect_b,NaN,800,128

In [60]:
defective_samples = df.loc[df['mask_rle'].notna()]
defective_samples.shape[0]

7201

In [61]:
most_frequent_count = defective_samples['defect_type'].value_counts().max()
most_frequent_count

np.int64(4100)

In [62]:
df['has_defect'] = df['mask_rle'].notnull()
df.head(5)

,image_id,defect_type,mask_rle,width,height,has_defect
0,4S22I7SA34,defect_a,7255 6 7377 12 7505 12 7633 12 7762 11 7890 11...,800,128,True
1,4S22I7SA34,defect_b,NaN,800,128,False
2,4S22I7SA34,defect_c,NaN,800,128,False
3,4S22I7SA34,defect_d,NaN,800,128,False
4,DZ899111OE,defect_a,NaN,800,128,False

In [63]:
defects_per_image = df.groupby('image_id')['has_defect'].sum()
clean_images_count = (defects_per_image==0).sum()
clean_images_count

np.int64(5516)

In [64]:
print(f"Most Frequent count + Clean Images count: {most_frequent_count+clean_images_count}")

Most Frequent count + Clean Images count: 9616

Question 2: Multi-Label Cardinality & Co-occurrence Complexity
While defect classes are reported across separate rows, industrial steel sheets can suffer from simultaneous manufacturing errors. Analyze the label cardinality (the number of distinct defect classes present per image) across all 11,393 images in train.csv.

Question: Exactly how many images in the training set exhibit multi-label defect co-occurrence (i.e., contain strictly more than 1 defect class)?

Answer format: Integer.

In [65]:
more_than_one_class_count = (defects_per_image>1).sum()
more_than_one_class_count

np.int64(1198)

Question 3: The Spatial Mutual-Exclusivity Proof (Architectural Insight)
Even if an image has multiple defects at the image level, the physical defects may or may not overlap spatially. Decode all masks for the multi-label images identified in Question 2 onto their native (128, 800) canvas.

Check whether any individual pixel carries annotations for two or more defect classes at the exact same spatial coordinate 
.

Question: What is the total count of overlapping defect pixels (pixels with 
 defect labels) across the entire training dataset?

Answer format: Short answer (exact count).

In [66]:
import os
import sys

sys.path.append(os.path.abspath('..'))
from src.utils import rle_to_mask
multi_label_image_ids = defects_per_image[defects_per_image>1].index
total_overlapping_pixels = 0

for img_id in multi_label_image_ids:
    img_df = df.loc[df['image_id']==img_id]
    img_df_defective = img_df[img_df['mask_rle'].notnull()]
    combined_mask = np.zeros((128,800))
    for rle_string,h,w in zip(img_df_defective['mask_rle'],img_df_defective['height'],img_df_defective['width']):
        decoded_mask  = rle_to_mask(rle_string,h,w)
        combined_mask+=decoded_mask
    overlap_count = np.sum(combined_mask>=2)
    total_overlapping_pixels+=overlap_count
print(total_overlapping_pixels)

0

Question 4: RLE Standards & The Boundary Edge Case (Production Data Cleaning)
The competition uses Kaggle/Severstal-style 1-based Fortran-order (column-major) Run-Length Encoding on a canvas of shape 
 pixels. A naive decoder assumes every run index strictly satisfies:

 <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mn>1</mn>
  <mo>&#x2264;</mo>
  <mtext>start</mtext>
  <mo>+</mo>
  <mtext>length</mtext>
  <mo>&#x2212;</mo>
  <mn>1</mn>
  <mo>&#x2264;</mo>
  <mn>102,400.</mn>
</math>

Inspect every non-empty RLE string in train.csv.

Question: Exactly how many rows in train.csv contain a malformed run where the end pixel index exceeds the canvas boundary (102,400), and what is the maximum pixel index encountered?

Answer format: X rows, max index Y.

In [ ]:
max_end_pixel = 0
for rle_string in defective_samples['mask_rle']:
    rle_str_list = rle_string.split()
    for s in range(0,len(rle_str_list),2):
        start_pixel = int(rle_str_list[s])
        length = int(rle_str_list[s+1])
        end_pixel = start_pixel+length-1
        if end_pixel>max_end_pixel:
            max_end_pixel = end_pixel
print(max_end_pixel)

102400

Question 5: Geometric Distortion & Anisotropic Aspect Ratio
Images have native resolution 
 (height × width). A standard deep learning practice in natural image segmentation is to resize inputs to a square 
 using bilinear interpolation, train the model, and resize predicted masks back to 
 via nearest neighbors. The forward resize applies its own scale factor to each axis: the horizontal scale factor 
 acts on width, and the vertical scale factor 
 acts on height.

Question: Compute 
 and 
 for the 
 resize, then the ratio of vertical stretching to horizontal compression, 
. (Mind which dimension — width or height — belongs in each ratio.)

Answer format: s_x, s_y, ratio.

In [119]:
## Source shape height - 128, width - 800
## Target shape height - 256, widht - 256

## Need to find Sx, Sy and Aspect Ratio

def Sx(Ws,Wt):
    return Wt/Ws
def Sy(Hs,Ht):
    return Ht/Hs

Hs,Ht = 128, 256
Ws,Wt = 800, 256

Sx = Sx(Ws,Wt)
print(f"Sx:{Sx}")
Sy = Sy(Hs,Ht)
print(f"Sy:{Sy}")

R = Sy/Sx
print(f"R:{R}")

Sx:0.32
Sy:2.0
R:6.25

Question 6: Photometric Invisibility & Defect Feature Types (Cohen's d)
For each defect class, calculate the pixel intensity distribution of the defect region versus the surrounding local background (outside defect, within the same image). The standardized mean difference is measured by Cohen's 
:

<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mi>d</mi>
  <mo>=</mo>
  <mfrac>
    <mrow>
      <msub>
        <mi>&#x3BC;</mi>
        <mrow data-mjx-texclass="ORD">
          <mtext>defect</mtext>
        </mrow>
      </msub>
      <mo>&#x2212;</mo>
      <msub>
        <mi>&#x3BC;</mi>
        <mrow data-mjx-texclass="ORD">
          <mtext>bg</mtext>
        </mrow>
      </msub>
    </mrow>
    <msub>
      <mi>&#x3C3;</mi>
      <mrow data-mjx-texclass="ORD">
        <mtext>pooled</mtext>
      </mrow>
    </msub>
  </mfrac>
  <mo>.</mo>
</math>
 
Question: Which defect class has a Cohen's 
 relative to its local background, rendering it photometrically invisible to pure grayscale thresholding methods, and what type of features (intensity vs. texture/frequency) are strictly required to detect it?

Answer format: Defect name and feature type: defect_name, feature_type.

In [116]:
import os
import cv2
import numpy as np
import pandas as pd
from src.utils import rle_to_mask

img_dir = r"D:\SurfaceGuard_AI\data\train"
defect_classes = ['defect_a','defect_b','defect_c','defect_d']
cohen_results = {}

for defect in defect_classes:
   sub_df = df[(df['defect_type']==defect) & (df['mask_rle'].notnull()).head(50)]
   d_list = []

   for _,row in sub_df.iterrows():
        img_path = os.path.join(img_dir,row['image_id']+'.jpg')
        if not os.path.exists(img_path):
            img_path = os.path.join(img_dir, row['image_id'])
        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

        # Decode the mask
        mask = rle_to_mask(row['mask_rle'],height=128,width=800)

        # Separate foreground defect pixels vs local background pixels
        fg = img[mask==1]
        bg = img[mask==0] 

        if len(fg) < 2 or len(bg) < 2:
            continue

        # Means and sample variance
        m1, s1 = np.mean(fg), np.var(fg,ddof=1)
        m2, s2 = np.mean(bg), np.var(bg,ddof=1)
        n1, n2 = len(fg), len(bg)
 
        # Pooled standard deviation
        sp = np.sqrt(((n1-1)*s1+(n2-1)*s2) / (n1+n2-2))

        if sp > 0:
            d = (m1 - m2) / sp
            d_list.append(d)

   cohen_results[defect] = np.mean(d_list)

# 2. Display the results for all 4 defect classes
for defect, d_val in cohen_results.items():
    print(f"{defect}: Chon's d = {d_val:.4f}")

defect_a: Chon's d = 0.3218
defect_b: Chon's d = 1.4449
defect_c: Chon's d = 0.7785
defect_d: Chon's d = 0.0301

Question 7: Metric Behavior — The Discontinuous Step Function of Naive Dice
In standard semantic segmentation, Dice between predicted binary mask 
 and ground truth mask 
 is defined as:

<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mi>Dice</mi>
  <mo stretchy="false">(</mo>
  <mi>X</mi>
  <mo>,</mo>
  <mi>Y</mi>
  <mo stretchy="false">)</mo>
  <mo>=</mo>
  <mfrac>
    <mrow>
      <mn>2</mn>
      <mrow data-mjx-texclass="ORD">
        <mo stretchy="false">|</mo>
      </mrow>
      <mi>X</mi>
      <mo>&#x2229;</mo>
      <mi>Y</mi>
      <mo stretchy="false">|</mo>
    </mrow>
    <mrow>
      <mo stretchy="false">|</mo>
      <mi>X</mi>
      <mrow data-mjx-texclass="ORD">
        <mo stretchy="false">|</mo>
      </mrow>
      <mo>+</mo>
      <mrow data-mjx-texclass="ORD">
        <mo stretchy="false">|</mo>
      </mrow>
      <mi>Y</mi>
      <mo stretchy="false">|</mo>
    </mrow>
  </mfrac>
  <mo>.</mo>
</math>
 
Use the standard empty convention <math xmlns="http://www.w3.org/1998/Math/MathML">
  <mi>Dice</mi>
  <mo stretchy="false">(</mo>
  <mi mathvariant="normal">&#x2205;</mi>
  <mo>,</mo>
  <mi mathvariant="normal">&#x2205;</mi>
  <mo stretchy="false">)</mo>
  <mo>=</mo>
  <mn>1.0</mn>
</math>: 
.

Suppose an image has no defect for defect_b (
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mi>Y</mi>
  <mo>=</mo>
  <mi mathvariant="normal">&#x2205;</mi>
</math>).

Model 1 predicts no defect (<math xmlns="http://www.w3.org/1998/Math/MathML">
  <msub>
    <mrow data-mjx-texclass="ORD">
      <mover>
        <mi>X</mi>
        <mo stretchy="false">^</mo>
      </mover>
    </mrow>
    <mn>1</mn>
  </msub>
  <mo>=</mo>
  <mi mathvariant="normal">&#x2205;</mi>
</math>
).
Model 2 predicts just 2 stray noise pixels (<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mo stretchy="false">|</mo>
  <msub>
    <mrow data-mjx-texclass="ORD">
      <mover>
        <mi>X</mi>
        <mo stretchy="false">^</mo>
      </mover>
    </mrow>
    <mn>2</mn>
  </msub>
  <mrow data-mjx-texclass="ORD">
    <mo stretchy="false">|</mo>
  </mrow>
  <mo>=</mo>
  <mn>2</mn>
</math>
).
Question: What is the Dice score for Model 1? What is the Dice score for Model 2?

Answer format: Numerical scores: Dice1, Dice2.

## Dice 1:
Since both prediction and ground truth is 0 the dice score is 1 for Model 1

## Dice 2:
Model 2 predicts 2 noise pixels so |A <mo>&#x2229;</mo> B| = 0 there would be no math and Dice Score for model 2 becomes 0

In [118]:
def compute_dice(pred_pixels,gt_pixels):
    if pred_pixels == 0 and gt_pixels == 0:
        return 1.0
    intersection = 0
    return (2.0 * intersection)/(pred_pixels + gt_pixels)

dice_1 = compute_dice(0,0)
dice_2 = compute_dice(2,0)

print(f"Dice 1:{dice_1}")
print(f"Dice 2: {dice_2}")

Dice 1:1.0
Dice 2: 0.0

Question 8: Official Competition Weighted Metric — Toy Batch Calculation
The competition organizers evaluate submissions using a weighted composite metric. For this assessment, use these component definitions:

<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mtext>Score</mtext>
  <mo>=</mo>
  <mn>0.70</mn>
  <mo>&#xD7;</mo>
  <mtext>ForegroundDice</mtext>
  <mo>+</mo>
  <mn>0.20</mn>
  <mo>&#xD7;</mo>
  <mtext>FalsePositiveScore</mtext>
  <mo>+</mo>
  <mn>0.10</mn>
  <mo>&#xD7;</mo>
  <mtext>EmptyAccuracy</mtext>
  <mo>.</mo>
</math>

ForegroundDice is the average Dice score computed strictly across image-defect pairs where a ground-truth defect exists (<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mo stretchy="false">|</mo>
  <mi>Y</mi>
  <mrow data-mjx-texclass="ORD">
    <mo stretchy="false">|</mo>
  </mrow>
  <mo>&gt;</mo>
  <mn>0</mn>
</math>
).

FalsePositiveScore is <math xmlns="http://www.w3.org/1998/Math/MathML">
  <mn>1</mn>
  <mo>&#x2212;</mo>
  <mtext>mean fp pixel fraction</mtext>
</math>
 across all ground-truth empty pairs (<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mo stretchy="false">|</mo>
  <mi>Y</mi>
  <mrow data-mjx-texclass="ORD">
    <mo stretchy="false">|</mo>
  </mrow>
  <mo>=</mo>
  <mn>0</mn>
</math>
), where the false-positive pixel fraction is 
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mo stretchy="false">|</mo>
  <mrow data-mjx-texclass="ORD">
    <mover>
      <mi>X</mi>
      <mo stretchy="false">^</mo>
    </mover>
  </mrow>
  <mrow data-mjx-texclass="ORD">
    <mo stretchy="false">|</mo>
  </mrow>
  <mrow data-mjx-texclass="ORD">
    <mo>/</mo>
  </mrow>
  <mn>102,400</mn>
</math>.

EmptyAccuracy is the proportion of ground-truth empty pairs (<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mo stretchy="false">|</mo>
  <mi>Y</mi>
  <mrow data-mjx-texclass="ORD">
    <mo stretchy="false">|</mo>
  </mrow>
  <mo>=</mo>
  <mn>0</mn>
</math>
) where the model correctly predicts an entirely empty mask (<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mo stretchy="false">|</mo>
  <mrow data-mjx-texclass="ORD">
    <mover>
      <mi>X</mi>
      <mo stretchy="false">^</mo>
    </mover>
  </mrow>
  <mrow data-mjx-texclass="ORD">
    <mo stretchy="false">|</mo>
  </mrow>
  <mo>=</mo>
  <mn>0</mn>
</math>
).

Consider a validation set of 50 image-class pairs:

10 pairs are positive (<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mo stretchy="false">|</mo>
  <mi>Y</mi>
  <mrow data-mjx-texclass="ORD">
    <mo stretchy="false">|</mo>
  </mrow>
  <mo>&gt;</mo>
  <mn>0</mn>
</math>
). The model achieves individual Dice scores of 0.80 on 6 pairs and 0.40 on 4 pairs.
40 pairs are empty (<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mo stretchy="false">|</mo>
  <mi>Y</mi>
  <mrow data-mjx-texclass="ORD">
    <mo stretchy="false">|</mo>
  </mrow>
  <mo>=</mo>
  <mn>0</mn>
</math>
). The model predicts completely empty masks on 36 pairs. On the remaining 4 pairs, it predicts false-positive blobs of 1,024 pixels each on a 102,400-pixel canvas.
Question: Calculate the exact values of:

(a) ForegroundDice
(b) FalsePositiveScore
(c) EmptyAccuracy
(d) Final weighted Score (rounded to 4 decimal places).

Answer format: a, b, c, d.

In [125]:
img_class_pairs = 50
postive_pairs = 10

# 6 pairs -> 0.80 and 4 pairs 0.40
empty_pairs = 40
predicted_empty_pairs = 36
wrong_empty_predictions_pairs = 4
false_positive_blobs_pixel = 1024
total_canvas_pixels = 102400

FG = ((6*0.80) + (4*0.40)) / postive_pairs

wrong_blob_pixels_percentage = false_positive_blobs_pixel / total_canvas_pixels

mean_fp_fraction = (36*0)+(4*wrong_blob_pixels_percentage)/ empty_pairs

FP = 1 - mean_fp_fraction

EA = predicted_empty_pairs / empty_pairs
EA

Final_weighted_Score = (0.70*FG) + (0.20*FP) + (0.10*EA)
print(f"FG:{FG}")
print(f"FP:{FP}")
print(f"EA:{EA}")
print(f"Final Weighted Score :{Final_weighted_Score:.4f}")

FG:0.64
FP:0.999
EA:0.9
Final Weighted Score :0.7378

Question 9: The “All-Empty Baseline” on the Full Training Set (No Splits Required)
You have only the raw Kaggle training data; no validation folds or trained models are needed for this question.

Consider the trivial “Always Abstain / All-Zeros” baseline: a predictor that outputs an empty mask <math xmlns="http://www.w3.org/1998/Math/MathML">
  <mrow data-mjx-texclass="ORD">
    <mover>
      <mi>X</mi>
      <mo stretchy="false">^</mo>
    </mover>
  </mrow>
  <mo>=</mo>
  <mi mathvariant="normal">&#x2205;</mi>
</math>
 for every image-class pair. Evaluate this baseline over all 45,572 image-class pairs in train.csv, using the empty convention from Question 7 (<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mi>Dice</mi>
  <mo stretchy="false">(</mo>
  <mi mathvariant="normal">&#x2205;</mi>
  <mo>,</mo>
  <mi mathvariant="normal">&#x2205;</mi>
  <mo stretchy="false">)</mo>
  <mo>=</mo>
  <mn>1.0</mn>
</math>
).

Question:

How many of the 45,572 image-class pairs have an empty ground-truth mask? Using that count, what is the naive empty-aware mean Dice score of the all-empty baseline (round to 4 decimal places)?

What is the official competition score of this exact same baseline (using the three component definitions from Question 8)?
Answer format: Score_naive, Score_official. Compute the empty-pair count as part of your working.

In [133]:
# Empty rows
empty_ground_truth_mask = df.loc[df['mask_rle'].isna()]
empty_wrong_prediction = df.loc[df['mask_rle'].notna()]
N = df.shape[0]
# Naive Mean Dice
N_empty = empty_ground_truth_mask.shape[0]
N_pos_wrong_empty = empty_wrong_prediction.shape[0]
N_empty,N_pos_wrong_empty
Naive_Mean_Dice = ((N_empty * (1.0)) + (N_pos_wrong_empty*(0.0))) / N
Naive_Mean_Dice

FG = 0.0 # Since model predicts all zeros on actual defects
FP = 1.0 # Model doesn't produce any false positive pixels on empty image
EA = 1.0

Score_official = (0.7*0.0) + (0.2*1.0) + (0.10*1.0)
Score_official
print(f"Empty Pairs Count:{N_empty}")
print(f"Naive Mean Dice: {Naive_Mean_Dice:.4f}")
print(f"Official Score:{Score_official:.4f}")

Empty Pairs Count:38371
Naive Mean Dice: 0.8420
Official Score:0.3000